{
 "title": "Koburst Default",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests by Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(request) (koburst_request_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (koburst_request_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    { "expr": "koburst_users_count", "legendFormat": "Users" }
   ]
  },
  {
   "title": "Requests by Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(status) (koburst_request_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per Minute",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(request) (rate(koburst_request_total[1m]))",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Request Rate by Status",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(koburst_request_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}